<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class city extends Model
{
    //
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            try{
                $model->id = Uuid::uuid4()->toString();
            }catch (UnsatisfiedDependencyException $e){
                abort(500, $e->getMessage());
            }
        });
    }

}
