<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Comment extends Model
{
    //
    protected $appends = array('children');

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            try{
                $model->id = Uuid::uuid4()->toString();
            }catch (UnsatisfiedDependencyException $e){
                abort(500, $e->getMessage());
            }
        });
    }

    protected $keyType = 'string';
    public $incrementing = false;

    public function getChildrenAttribute(){
        $id = $this->attributes['id'];
        $data = Comment::where('parent_id', $id)->get();
        if(sizeof($data)==0) return null;
        return $data;
    }

    public function getUserIdAttribute(){
        $user_id = $this->attributes['user_id'];
        $data = User::where('id', $user_id)->get();
        return $data[0];
    }
}
