<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Ramsey\Uuid\Uuid;

class PublicFacilities extends Model
{
    //
    use SoftDeletes;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            try{
                $model->id = Uuid::uuid4()->toString();
            }catch (UnsatisfiedDependencyException $e){
                abort(500, $e->getMessage());
            }
        });
    }

    protected $keyType = 'string';
    public $incrementing = false;

    public function PublicFacilitiesDetail(){
        return $this->hasOne(properties::class, 'id', 'property_id');
    }

}
